// /////////////////////////////////////////////////////////////////
// Generated by dtkPluginGenerator
// /////////////////////////////////////////////////////////////////

#ifndef EDPROCESSTEXTGENERATOR_H
#define EDPROCESSTEXTGENERATOR_H

#include <dtkCore/dtkAbstractProcess.h>

#include "edProcessTextGeneratorPluginExport.h"

class edProcessTextGeneratorPrivate;

class EDPROCESSTEXTGENERATORPLUGIN_EXPORT edProcessTextGenerator : public dtkAbstractProcess
{
    Q_OBJECT

public:
             edProcessTextGenerator(void);
    virtual ~edProcessTextGenerator(void);

    virtual QString description(void) const;

    static bool registered(void);

    virtual dtkAbstractData *output(void);

    virtual int update(void);

private:
    edProcessTextGeneratorPrivate *d;
};

dtkAbstractProcess *createEdProcessTextGenerator(void);

#endif
