// /////////////////////////////////////////////////////////////////
// Generated by dtkPluginGenerator
// /////////////////////////////////////////////////////////////////

#ifndef EDPROCESSTEXTGENERATORPLUGINEXPORT_H
#define EDPROCESSTEXTGENERATORPLUGINEXPORT_H

#ifdef WIN32
    #ifdef edProcessTextGeneratorPlugin_EXPORTS
        #define EDPROCESSTEXTGENERATORPLUGIN_EXPORT __declspec(dllexport) 
    #else
        #define EDPROCESSTEXTGENERATORPLUGIN_EXPORT __declspec(dllimport) 
    #endif
#else
    #define EDPROCESSTEXTGENERATORPLUGIN_EXPORT
#endif

#endif
