// /////////////////////////////////////////////////////////////////
// Generated by dtkPluginGenerator
// /////////////////////////////////////////////////////////////////

#ifndef EDPROCESSTEXTGENERATORPLUGIN_H
#define EDPROCESSTEXTGENERATORPLUGIN_H

#include <dtkCore/dtkPlugin.h>

#include "edProcessTextGeneratorPluginExport.h"

class EDPROCESSTEXTGENERATORPLUGIN_EXPORT edProcessTextGeneratorPluginPrivate;

class EDPROCESSTEXTGENERATORPLUGIN_EXPORT edProcessTextGeneratorPlugin : public dtkPlugin
{
    Q_OBJECT
    Q_INTERFACES(dtkPlugin)

public:
     edProcessTextGeneratorPlugin(QObject *parent = 0);
    ~edProcessTextGeneratorPlugin(void);

    virtual bool initialize(void);
    virtual bool uninitialize(void);

    virtual QString name(void) const;
    virtual QString description(void) const;

    virtual QStringList tags(void) const;
    virtual QStringList types(void) const;

private:
     edProcessTextGeneratorPluginPrivate *d;
};

#endif
