// /////////////////////////////////////////////////////////////////
// Generated by dtkPluginGenerator
// /////////////////////////////////////////////////////////////////

#ifndef EDDATATEXTPLUGINEXPORT_H
#define EDDATATEXTPLUGINEXPORT_H

#ifdef WIN32
    #ifdef edDataTextPlugin_EXPORTS
        #define EDDATATEXTPLUGIN_EXPORT __declspec(dllexport) 
    #else
        #define EDDATATEXTPLUGIN_EXPORT __declspec(dllimport) 
    #endif
#else
    #define EDDATATEXTPLUGIN_EXPORT
#endif

#endif
