// /////////////////////////////////////////////////////////////////
// Generated by dtkPluginGenerator
// /////////////////////////////////////////////////////////////////

#ifndef EDDATATEXTPLUGIN_H
#define EDDATATEXTPLUGIN_H

#include <dtkCore/dtkPlugin.h>

#include "edDataTextPluginExport.h"

class EDDATATEXTPLUGIN_EXPORT edDataTextPluginPrivate;

class EDDATATEXTPLUGIN_EXPORT edDataTextPlugin : public dtkPlugin
{
    Q_OBJECT
    Q_INTERFACES(dtkPlugin)

public:
     edDataTextPlugin(QObject *parent = 0);
    ~edDataTextPlugin(void);

    virtual bool initialize(void);
    virtual bool uninitialize(void);

    virtual QString name(void) const;
    virtual QString description(void) const;

    virtual QStringList tags(void) const;
    virtual QStringList types(void) const;

private:
     edDataTextPluginPrivate *d;
};

#endif
