// /////////////////////////////////////////////////////////////////
// Generated by dtkPluginGenerator
// /////////////////////////////////////////////////////////////////

#include "edViewText.h"
#include "edViewTextPlugin.h"

#include <dtkCore/dtkLog.h>

// /////////////////////////////////////////////////////////////////
// edViewTextPluginPrivate
// /////////////////////////////////////////////////////////////////

class edViewTextPluginPrivate 
{
public:
    // Class variables go here.
};

// /////////////////////////////////////////////////////////////////
// edViewTextPlugin
// /////////////////////////////////////////////////////////////////

edViewTextPlugin::edViewTextPlugin(QObject *parent) : dtkPlugin(parent), d(new edViewTextPluginPrivate)
{

}

edViewTextPlugin::~edViewTextPlugin(void)
{
    delete d;

    d = NULL;
}

bool edViewTextPlugin::initialize(void)
{
    if(!edViewText::registered())
	dtkWarning() << "Unable to register edViewText type";

    return true;
}

bool edViewTextPlugin::uninitialize(void)
{
    return true;
}

QString edViewTextPlugin::name(void) const
{
    return "edViewTextPlugin";
}

QString edViewTextPlugin::description(void) const
{
    return "";
}

QStringList edViewTextPlugin::tags(void) const
{
    return QStringList();
}

QStringList edViewTextPlugin::types(void) const
{
    return QStringList() << "edViewText";
}

Q_EXPORT_PLUGIN2(edViewTextPlugin, edViewTextPlugin)
