// /////////////////////////////////////////////////////////////////
// Generated by dtkPluginGenerator
// /////////////////////////////////////////////////////////////////

#ifndef EDVIEWTEXTPLUGIN_H
#define EDVIEWTEXTPLUGIN_H

#include <dtkCore/dtkPlugin.h>

#include "edViewTextPluginExport.h"

class EDVIEWTEXTPLUGIN_EXPORT edViewTextPluginPrivate;

class EDVIEWTEXTPLUGIN_EXPORT edViewTextPlugin : public dtkPlugin
{
    Q_OBJECT
    Q_INTERFACES(dtkPlugin)

public:
     edViewTextPlugin(QObject *parent = 0);
    ~edViewTextPlugin(void);

    virtual bool initialize(void);
    virtual bool uninitialize(void);

    virtual QString name(void) const;
    virtual QString description(void) const;

    virtual QStringList tags(void) const;
    virtual QStringList types(void) const;

private:
     edViewTextPluginPrivate *d;
};

#endif
