// /////////////////////////////////////////////////////////////////
// Generated by dtkPluginGenerator
// /////////////////////////////////////////////////////////////////

#ifndef EDVIEWTEXT_H
#define EDVIEWTEXT_H

#include <dtkCore/dtkAbstractView.h>

#include "edViewTextPluginExport.h"

class edViewTextPrivate;

class EDVIEWTEXTPLUGIN_EXPORT edViewText : public dtkAbstractView
{
    Q_OBJECT

public:
             edViewText(void);
    virtual ~edViewText(void);

    virtual QString description(void) const;

    static bool registered(void);

    virtual void setData(dtkAbstractData *data);

    QWidget *widget(void);
private:
    edViewTextPrivate *d;
};

dtkAbstractView *createEdViewText(void);

#endif
