// /////////////////////////////////////////////////////////////////
// Generated by dtkPluginGenerator
// /////////////////////////////////////////////////////////////////

#ifndef EDVIEWTEXTPLUGINEXPORT_H
#define EDVIEWTEXTPLUGINEXPORT_H

#ifdef WIN32
    #ifdef edViewTextPlugin_EXPORTS
        #define EDVIEWTEXTPLUGIN_EXPORT __declspec(dllexport) 
    #else
        #define EDVIEWTEXTPLUGIN_EXPORT __declspec(dllimport) 
    #endif
#else
    #define EDVIEWTEXTPLUGIN_EXPORT
#endif

#endif
